@startuml Files

title Files class diagram
class Storage {
    File[] files
}
enum Extension{
    DOCUMENT
    IMAGE
    AUDIO
    VIDEO
    OTHER
}
class File {
    String name
    byte size
    Extension extension
}

@enduml