@startuml Files
title Files class diagram

enum Extension{
    DOCUMENT
    IMAGE
    AUDIO
    VIDEO
    OTHER
}
class File {
    String name
    byte size
    Extension extension
}
class Document{
    String format
    int lists
}
class Image{

}
class Audio{

}
class Video{

}

Extension -> File
File -> Document
File -> Image
File -> Audio
File -> Video

class Storage {
    File[] files
    File[] getDefaultList()
    void print()
}

@enduml