@startuml Files
title Files class diagram
class Storage {
    Extension extension
    String readAnnotation()
    void main
}
enum Extension{
    DOCUMENT
    IMAGE
    AUDIO
    VIDEO
    OTHER
}
annotation File {
    String name()
    byte size()
    Extension extension ()
}

@enduml